//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ordertbl
    {
        
        public int Id { get; set; }
        public string Orderno { get; set; }
        public string Orderdate { get; set; }
        public int CustomerId { get; set; }
        public string Totalamount { get; set; }

        public Custom Customer { get; set; }

       

    }
}
